import { defineConfig } from 'vite'
import { devtools } from '@tanstack/devtools-vite'

import { tanstackStart } from '@tanstack/react-start/plugin/vite'

import viteReact from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// Note: the service worker is generated by scripts/generate-sw.mjs as a
// post-build step (`npm run build` runs it after `vite build`). vite-plugin-pwa
// skips SSR/environment builds, so under TanStack Start's multi-environment
// build it never emits sw.js — running workbox-build directly is deterministic.
const config = defineConfig({
  resolve: { tsconfigPaths: true },
  // The @jsquash codecs resolve their `.wasm` binaries via `import.meta.url`.
  // esbuild's dep pre-bundling rewrites that and breaks the lookup, so exclude
  // them — each codec is dynamically imported and its wasm emitted as an asset.
  optimizeDeps: {
    exclude: [
      '@jsquash/jpeg',
      '@jsquash/png',
      '@jsquash/oxipng',
      '@jsquash/webp',
      '@jsquash/avif',
      '@jsquash/jxl',
    ],
  },
  // Pin the preview server (used by TanStack Start's prerender step) to IPv4.
  // In minimal containers `localhost` resolves to both 127.0.0.1 and ::1; the
  // preview server and the prerender fetch can otherwise pick different families,
  // producing a ConnectionRefused during `vite build`'s prerender.
  preview: { host: '127.0.0.1' },
  plugins: [
    devtools(),
    tailwindcss(),
    // SPA / static mode: emit a static SPA shell so the app deploys to any
    // static host (GitHub Pages, Cloudflare, Netlify) with no backend. All
    // image processing runs client-side, so there is nothing to render server-side.
    tanstackStart({ spa: { enabled: true } }),
    viteReact(),
  ],
})

export default config
