import { defineConfig } from 'vite'
import { devtools } from '@tanstack/devtools-vite'

import { tanstackStart } from '@tanstack/react-start/plugin/vite'

import viteReact from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// Note: the service worker is generated by scripts/generate-sw.mjs as a
// post-build step (`npm run build` runs it after `vite build`). vite-plugin-pwa
// skips SSR/environment builds, so under TanStack Start's multi-environment
// build it never emits sw.js — running workbox-build directly is deterministic.
const config = defineConfig({
  resolve: { tsconfigPaths: true },
  plugins: [
    devtools(),
    tailwindcss(),
    // SPA / static mode: emit a static SPA shell so the app deploys to any
    // static host (GitHub Pages, Cloudflare, Netlify) with no backend. All
    // image processing runs client-side, so there is nothing to render server-side.
    tanstackStart({ spa: { enabled: true } }),
    viteReact(),
  ],
})

export default config
