import { useEffect, useRef, useState } from 'react'
import RefreshCw from 'lucide-react/dist/esm/icons/refresh-cw'
import { Button } from '#/components/ui/button.tsx'

/**
 * Registers the Workbox service worker (generated by scripts/generate-sw.mjs)
 * and surfaces a reload prompt when a new version has been installed. Only runs
 * in production builds where /sw.js exists. Renders nothing until an update is
 * waiting.
 */
export function PwaUpdater() {
  const [waiting, setWaiting] = useState<ServiceWorker | null>(null)
  // Only reload on controllerchange that the user actually triggered — the
  // first-load clientsClaim also fires controllerchange and must be ignored.
  const userConfirmedRef = useRef(false)

  useEffect(() => {
    if (import.meta.env.DEV) return
    if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
      return
    }

    let cancelled = false

    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then((reg) => {
        if (cancelled) return

        // A worker already waiting (updated in a previous session/tab).
        if (reg.waiting && navigator.serviceWorker.controller) {
          setWaiting(reg.waiting)
        }

        reg.addEventListener('updatefound', () => {
          const installing = reg.installing
          if (!installing) return
          installing.addEventListener('statechange', () => {
            // Installed + an existing controller ⇒ this is an update, not first install.
            if (
              installing.state === 'installed' &&
              navigator.serviceWorker.controller
            ) {
              setWaiting(reg.waiting ?? installing)
            }
          })
        })

        // Registration checks can be throttled by the browser. Explicitly ask
        // for a fresh sw.js so every visit can surface a waiting deployment.
        void reg.update().catch(() => {
          // Stay on the current version when the update check is offline/fails.
        })
      })
      .catch(() => {
        // No SW in dev or when unsupported — the app still works online.
      })

    // Reload once the user-activated worker takes control. Ignored on the
    // first-visit claim (userConfirmedRef is still false then).
    let reloading = false
    const onControllerChange = () => {
      if (!userConfirmedRef.current || reloading) return
      reloading = true
      window.location.reload()
    }
    navigator.serviceWorker.addEventListener(
      'controllerchange',
      onControllerChange,
    )

    return () => {
      cancelled = true
      navigator.serviceWorker.removeEventListener(
        'controllerchange',
        onControllerChange,
      )
    }
  }, [])

  if (!waiting) return null

  const reload = () => {
    // Ask the waiting worker to activate; controllerchange then reloads.
    userConfirmedRef.current = true
    waiting.postMessage({ type: 'SKIP_WAITING' })
  }

  return (
    <div
      role="status"
      className="border-border bg-popover text-popover-foreground fixed right-4 bottom-4 z-[60] flex max-w-[calc(100vw-2rem)] items-center gap-4 rounded-xl border px-4 py-3 shadow-[var(--overlay-shadow)]"
    >
      <RefreshCw className="text-brand size-4 shrink-0" aria-hidden />
      <span className="text-sm">A new version is ready.</span>
      <Button size="sm" onClick={reload}>
        Reload
      </Button>
    </div>
  )
}
