import { useEffect } from 'react'

/**
 * Registers the Workbox service worker (generated by scripts/generate-sw.mjs)
 * and reloads the page as soon as a new version takes control. Updates are
 * fully automatic (skipWaiting + clientsClaim in generate-sw.mjs) — there is
 * no user-facing prompt, and a reload can interrupt in-progress work. Only
 * runs in production builds where /sw.js exists. Renders nothing.
 */
export function PwaUpdater() {
  useEffect(() => {
    if (import.meta.env.DEV) return
    if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
      return
    }

    // A controller already present at mount means this tab was already being
    // served by a worker (a normal repeat visit) — any later controllerchange
    // is therefore a real update. With no controller yet (first-ever visit,
    // or cleared site data), the very first controllerchange is just this
    // worker taking initial control and must not reload the page.
    let hadController = Boolean(navigator.serviceWorker.controller)
    let reloading = false

    const onControllerChange = () => {
      if (reloading) return
      if (!hadController) {
        hadController = true
        return
      }
      reloading = true
      window.location.reload()
    }
    navigator.serviceWorker.addEventListener(
      'controllerchange',
      onControllerChange,
    )

    let cancelled = false
    let registration: ServiceWorkerRegistration | undefined

    const checkForUpdate = () => {
      if (document.visibilityState !== 'visible') return
      void registration?.update().catch(() => {
        // Stay on the current version when the update check is offline/fails.
      })
    }
    document.addEventListener('visibilitychange', checkForUpdate)
    window.addEventListener('focus', checkForUpdate)

    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then((reg) => {
        if (cancelled) return
        registration = reg
        // Registration checks can be throttled by the browser. Explicitly ask
        // for a fresh sw.js so every visit can surface a new deployment.
        void reg.update().catch(() => {
          // Stay on the current version when the update check is offline/fails.
        })
      })
      .catch(() => {
        // No SW in dev or when unsupported — the app still works online.
      })

    return () => {
      cancelled = true
      document.removeEventListener('visibilitychange', checkForUpdate)
      window.removeEventListener('focus', checkForUpdate)
      navigator.serviceWorker.removeEventListener(
        'controllerchange',
        onControllerChange,
      )
    }
  }, [])

  return null
}
