import { useEffect } from 'react'

/**
 * Registers the Workbox service worker (generated by scripts/generate-sw.mjs)
 * and checks for updates whenever the app is revisited. The worker lifecycle
 * script owns upgrade navigation so it can refresh pages running older app
 * bundles too. Only runs in production builds where /sw.js exists. Renders
 * nothing.
 */
export function PwaUpdater() {
  useEffect(() => {
    if (import.meta.env.DEV) return
    if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
      return
    }

    let cancelled = false
    let registration: ServiceWorkerRegistration | undefined

    const checkForUpdate = () => {
      if (document.visibilityState !== 'visible') return
      void registration?.update().catch(() => {
        // Stay on the current version when the update check is offline/fails.
      })
    }
    document.addEventListener('visibilitychange', checkForUpdate)
    window.addEventListener('focus', checkForUpdate)

    navigator.serviceWorker
      .register('/sw.js', { scope: '/', updateViaCache: 'none' })
      .then((reg) => {
        if (cancelled) return
        registration = reg
        // Registration checks can be throttled by the browser. Explicitly ask
        // for a fresh sw.js so every visit can surface a new deployment.
        void reg.update().catch(() => {
          // Stay on the current version when the update check is offline/fails.
        })
      })
      .catch(() => {
        // No SW in dev or when unsupported — the app still works online.
      })

    return () => {
      cancelled = true
      document.removeEventListener('visibilitychange', checkForUpdate)
      window.removeEventListener('focus', checkForUpdate)
    }
  }, [])

  return null
}
